# Generated by Django 2.1.15 on 2020-03-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200329_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocollection',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
