# Generated by Django 2.1.15 on 2020-03-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_portfoliocollection_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
